// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj93_uOoi334zxhYRHowmKUEjInhnGM-I',
    appId: '1:106130483704:web:4d578818e2de2d31a00e0d',
    messagingSenderId: '106130483704',
    projectId: 'runrace-ee966',
    authDomain: 'runrace-ee966.firebaseapp.com',
    storageBucket: 'runrace-ee966.firebasestorage.app',
    measurementId: 'G-D83M3GWDTR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxTtn-MmrxBQV77Qr_uGfNMeNR9JuA1a0',
    appId: '1:106130483704:android:8dcc19f791ad4ce3a00e0d',
    messagingSenderId: '106130483704',
    projectId: 'runrace-ee966',
    storageBucket: 'runrace-ee966.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABmo4-aJ2BiTAel6Q4tHHmZMdrkDBRs90',
    appId: '1:106130483704:ios:310a3d940552f11fa00e0d',
    messagingSenderId: '106130483704',
    projectId: 'runrace-ee966',
    storageBucket: 'runrace-ee966.firebasestorage.app',
    androidClientId: '106130483704-q5b0v5vmvb9thmagc34avspn9d6lgn54.apps.googleusercontent.com',
    iosClientId: '106130483704-idgn7deqqmuqt24l4bf6gulh1beeij3e.apps.googleusercontent.com',
    iosBundleId: 'com.example.notracerunApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABmo4-aJ2BiTAel6Q4tHHmZMdrkDBRs90',
    appId: '1:106130483704:ios:310a3d940552f11fa00e0d',
    messagingSenderId: '106130483704',
    projectId: 'runrace-ee966',
    storageBucket: 'runrace-ee966.firebasestorage.app',
    androidClientId: '106130483704-q5b0v5vmvb9thmagc34avspn9d6lgn54.apps.googleusercontent.com',
    iosClientId: '106130483704-idgn7deqqmuqt24l4bf6gulh1beeij3e.apps.googleusercontent.com',
    iosBundleId: 'com.example.notracerunApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCj93_uOoi334zxhYRHowmKUEjInhnGM-I',
    appId: '1:106130483704:web:b5fdcf908ef86db9a00e0d',
    messagingSenderId: '106130483704',
    projectId: 'runrace-ee966',
    authDomain: 'runrace-ee966.firebaseapp.com',
    storageBucket: 'runrace-ee966.firebasestorage.app',
    measurementId: 'G-NP4KE1RYX2',
  );
}
